# TCL File Generated by Component Editor 9.1sp2
# Sat Apr 17 16:22:12 CEST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | uart "uart" v1.0
# | Iztok Jeras 2010.04.17.16:22:12
# | simple UART without a fifo
# | 
# | /home/izi/Workplace/fpga-hdl/hdl/uart/uart.v
# | 
# |    ./uart.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module uart
# | 
set_module_property DESCRIPTION "simple UART without a fifo"
set_module_property NAME uart
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property AUTHOR "Iztok Jeras"
set_module_property DISPLAY_NAME uart
set_module_property TOP_LEVEL_HDL_FILE uart.v
set_module_property TOP_LEVEL_HDL_MODULE uart
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file uart.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter BYTESIZE INTEGER 8
set_parameter_property BYTESIZE DEFAULT_VALUE 8
set_parameter_property BYTESIZE DISPLAY_NAME BYTESIZE
set_parameter_property BYTESIZE UNITS None
set_parameter_property BYTESIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTESIZE DISPLAY_HINT ""
set_parameter_property BYTESIZE AFFECTS_GENERATION false
set_parameter_property BYTESIZE HDL_PARAMETER true
add_parameter PARITY STRING NONE
set_parameter_property PARITY DEFAULT_VALUE NONE
set_parameter_property PARITY DISPLAY_NAME PARITY
set_parameter_property PARITY UNITS None
set_parameter_property PARITY DISPLAY_HINT ""
set_parameter_property PARITY AFFECTS_GENERATION false
set_parameter_property PARITY HDL_PARAMETER true
add_parameter STOPSIZE INTEGER 1
set_parameter_property STOPSIZE DEFAULT_VALUE 1
set_parameter_property STOPSIZE DISPLAY_NAME STOPSIZE
set_parameter_property STOPSIZE UNITS None
set_parameter_property STOPSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property STOPSIZE DISPLAY_HINT ""
set_parameter_property STOPSIZE AFFECTS_GENERATION false
set_parameter_property STOPSIZE HDL_PARAMETER true
add_parameter N_BIT INTEGER 2
set_parameter_property N_BIT DEFAULT_VALUE 2
set_parameter_property N_BIT DISPLAY_NAME N_BIT
set_parameter_property N_BIT UNITS None
set_parameter_property N_BIT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_BIT DISPLAY_HINT ""
set_parameter_property N_BIT AFFECTS_GENERATION false
set_parameter_property N_BIT HDL_PARAMETER true
add_parameter AAW INTEGER 1
set_parameter_property AAW DEFAULT_VALUE 1
set_parameter_property AAW DISPLAY_NAME AAW
set_parameter_property AAW UNITS None
set_parameter_property AAW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AAW DISPLAY_HINT ""
set_parameter_property AAW AFFECTS_GENERATION false
set_parameter_property AAW HDL_PARAMETER true
add_parameter ADW INTEGER 32
set_parameter_property ADW DEFAULT_VALUE 32
set_parameter_property ADW DISPLAY_NAME ADW
set_parameter_property ADW UNITS None
set_parameter_property ADW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADW DISPLAY_HINT ""
set_parameter_property ADW AFFECTS_GENERATION false
set_parameter_property ADW HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave associatedClock clock_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avalon_read read Input 1
add_interface_port avalon_slave avalon_write write Input 1
add_interface_port avalon_slave avalon_writedata writedata Input ADW
add_interface_port avalon_slave avalon_readdata readdata Output ADW
add_interface_port avalon_slave avalon_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt
# | 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint avalon_slave

set_interface_property interrupt ASSOCIATED_CLOCK clock_reset
set_interface_property interrupt ENABLED true

add_interface_port interrupt avalon_interrupt irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit
# | 
add_interface conduit conduit end

set_interface_property conduit ASSOCIATED_CLOCK clock_reset
set_interface_property conduit ENABLED true

add_interface_port conduit uart_rxd export Input 1
add_interface_port conduit uart_txd export Output 1
# | 
# +-----------------------------------
